# Generated by Django 5.2.7 on 2025-10-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emis_no', models.CharField(max_length=20, unique=True)),
                ('umis_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=5)),
                ('religion', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('caste', models.CharField(max_length=50)),
                ('aadhar_no', models.CharField(max_length=12)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_cert_no', models.CharField(blank=True, max_length=50)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_city', models.CharField(max_length=50)),
                ('bank_branch', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('account_no', models.CharField(max_length=20)),
                ('account_type', models.CharField(max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('medium', models.CharField(max_length=20)),
                ('mode_of_study', models.CharField(max_length=20)),
                ('year_of_study', models.IntegerField()),
            ],
        ),
    ]
